name: GITHUB_ENV
run-name: GITHUB_ENV
on: push
jobs:
  share:
      name: share
      runs-on: ubuntu-latest
      steps:
        - name: step1
          run: echo "step1"
        - run: echo "RESULT=hello" >> "${GITHUB_ENV}"
        - run: echo "${RESULT}"
